"""Service configuration — every environment-dependent value the API needs, in one place.

Uses pydantic-settings, which reads each field from an environment variable of the same
name (case-insensitive) and validates its type, falling back to the default here. The
point is that the container (Phase 8) and the CI runner (Phase 9) configure this service
purely through the environment, with no code change and no config file baked into the image.

THE ONE RULE THIS FILE ENFORCES: an unconfigured deployment must be free and offline.
`sut` inherits the seam's default of "mock", and `allow_judge` defaults to False, so a
container started with no environment at all cannot download a model or spend money. The
expensive paths must be switched ON deliberately, never left on by inheritance.

PSEUDOCODE
    1. Settings(BaseSettings) with env_prefix="GUARDRAIL_":
       - sut / adapter_path / adapter_checkpoint -> forwarded to get_sut()
       - data_dir / runs_dir / benchmarks_dir    -> where corpus, runs, baselines live
       - allow_judge                            -> server-level kill switch for paid grading
       - max_prompt_chars                       -> input bound on /evaluate
    2. Derived paths: baselines_path, gate_policy_path.
    3. get_settings(): lru_cached singleton, and the FastAPI dependency for config.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

from guardrail.dataset.loader import DATASET_DIR

def _repo_root() -> Path:
    """Where the non-package files (benchmarks/, runs/) live.

    `benchmarks/` and `runs/` are the two things this project keeps OUTSIDE the package
    on purpose: baselines.json is a committed record of measurements, and runs/ is
    gitignored output. Neither ships in the wheel, so their location has to be found
    rather than imported — unlike the corpus, which is inside the package and therefore
    never needs any of this.

    Walking up from __file__ is right for an editable install (the dev machine) and
    WRONG for a real wheel: in a container __file__ sits in site-packages, so parents[3]
    is `/usr/local/lib/python3.13` and every benchmarks path silently points at a
    directory that does not exist. That failed as a 404 on /benchmarks and a dozen red
    tests the first time the suite ran inside the image (Phase 8).

    So the guess is VERIFIED before it is used, and falls back to the working directory,
    which is where a deployment naturally puts these files (`WORKDIR /app` + `COPY
    benchmarks/`). `GUARDRAIL_BENCHMARKS_DIR` / `GUARDRAIL_RUNS_DIR` override both, and
    the container sets them explicitly — this function only decides the default.
    """
    candidate = Path(__file__).resolve().parents[3]
    if (candidate / "pyproject.toml").is_file() or (candidate / "benchmarks").is_dir():
        return candidate
    return Path.cwd()


REPO_ROOT = _repo_root()


class Settings(BaseSettings):
    """Runtime configuration, read from the environment with GUARDRAIL_ prefixed names."""

    model_config = SettingsConfigDict(
        env_prefix="GUARDRAIL_",
        env_file=".env",
        extra="ignore",
    )

    # --- which system under test the service serves -------------------------------
    # Matches $GUARDRAIL_SUT, the same variable the CLI already honours, so the service
    # and the scripts can never disagree about which model is loaded.
    sut: str = "mock"
    adapter_path: str = "adapters/v2"
    adapter_checkpoint: int | None = None

    # --- where things live --------------------------------------------------------
    # The corpus lives INSIDE the package (src/guardrail/dataset/data/), not at the repo
    # root. That is what makes it ship with the wheel — so the container and the CI
    # runner have all 662 prompts without a data volume or a download step.
    data_dir: Path = DATASET_DIR
    runs_dir: Path = REPO_ROOT / "runs"
    benchmarks_dir: Path = REPO_ROOT / "benchmarks"

    # --- cost safety --------------------------------------------------------------
    # A server-level kill switch, distinct from the per-request `use_judge` flag. Both
    # must be on for a paid call to happen: the request must ask, and the deployment
    # must permit. Default off means the Docker image cannot spend money even if some
    # caller sets use_judge=true, which is the failure mode worth engineering against —
    # a demo left running with an open port should never be a billing hole.
    allow_judge: bool = False

    # Bound on /evaluate input. Not a security control, a cost/latency one: generation
    # time scales with prompt length, and an unbounded prompt is an unbounded request.
    max_prompt_chars: int = Field(default=8_000, gt=0)

    @property
    def baselines_path(self) -> Path:
        """Committed, machine-readable baselines — regenerated by write_benchmarks.py."""
        return self.benchmarks_dir / "baselines.json"

    @property
    def gate_policy_path(self) -> Path:
        """Hand-edited thresholds. See gate.GatePolicy for why these are kept apart."""
        return self.benchmarks_dir / "gate_policy.json"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """The process-wide Settings singleton, and the FastAPI dependency for config.

    Cached so that every endpoint sees identical configuration for the life of the
    process — config that can change between two requests is a debugging nightmare.
    Tests clear the cache (`get_settings.cache_clear()`) or override the dependency.
    """
    return Settings()


__all__ = ["REPO_ROOT", "Settings", "get_settings"]
